// smart-admin-web/src/views/support/message/message-list.vue
<template>
  <!---------- 查询表单form begin ----------->
  <a-form class="smart-query-form">
    <a-row class="smart-query-form-row">
      <a-form-item label="关键词" class="smart-query-form-item">
        <a-input style="width: 150px" v-model:value="queryForm.searchWord" placeholder="关键词" />
      </a-form-item>
      <a-form-item label="类型" class="smart-query-form-item">
        <smart-enum-select style="width: 150px" v-model:value="queryForm.messageType" placeholder="消息类型" enum-name="MESSAGE_TYPE_ENUM" />
      </a-form-item>
      <a-form-item label="是否已读" class="smart-query-form-item">
        <SmartEnumSelect width="120px" enum-name="FLAG_NUMBER_ENUM" v-model:value="queryForm.readFlag" />
      </a-form-item>
      <a-form-item label="创建时间" class="smart-query-form-item">
        <a-range-picker v-model:value="queryForm.createTime" style="width: 200px" @change="onChangeCreateTime" />
      </a-form-item>
      <a-form-item class="smart-query-form-item">
        <a-button type="primary" @click="searchQuery">
          <template #icon>
            <SearchOutlined />
          </template>
          查询
        </a-button>
        <a-button @click="resetQuery" class="smart-margin-left10">
          <template #icon>
            <ReloadOutlined />
          </template>
          重置
        </a-button>
      </a-form-item>
    </a-row>
  </a-form>
  <!---------- 查询表单form end ----------->

  <a-card size="small" :bordered="false" :hoverable="true">
    <!---------- 表格操作行 begin ----------->
    <a-row class="smart-table-btn-block">
      <div class="smart-table-operate-block">
        <a-button @click="showForm" type="primary">
          <template #icon>
            <PlusOutlined />
          </template>
          发送消息
        </a-button>
      </div>
      <div class="smart-table-setting-block">
        <TableOperator v-model="columns" :tableId="TABLE_ID_CONST.SUPPORT.MAIL" :refresh="queryData" />
      </div>
    </a-row>
    <!---------- 表格操作行 end ----------->

    <!---------- 表格 begin ----------->
    <a-table size="small" :dataSource="tableData" :columns="columns" rowKey="telephoneId" bordered :loading="tableLoading" :pagination="false">
      <template #bodyCell="{ record, column, text }">
        <template v-if="column.dataIndex === 'createTime'">
          {{ formatDateTime(text) }}
        </template>

        <template v-if="column.dataIndex === 'readFlag'">
          {{ text ? '已读' : '未读' }}
        </template>
        <template v-if="column.dataIndex === 'messageType'">
          {{ $smartEnumPlugin.getDescByValue('MESSAGE_TYPE_ENUM', text) }}
        </template>
        <template v-if="column.dataIndex === 'action'">
          <div class="smart-table-operate">
            <a-button @click="onDelete(record)" danger type="link">删除</a-button>
          </div>
        </template>
      </template>
    </a-table>
    <!---------- 表格 end ----------->

    <div class="smart-query-table-page">
      <a-pagination
        showSizeChanger
        showQuickJumper
        show-less-items
        :pageSizeOptions="PAGE_SIZE_OPTIONS"
        :defaultPageSize="queryForm.pageSize"
        v-model:current="queryForm.pageNum"
        v-model:pageSize="queryForm.pageSize"
        :total="total"
        @change="queryData"
        :show-total="(total) => `共${total}条`"
      />
    </div>

    <MessageSendForm ref="formRef" @reloadList="queryData" />
  </a-card>
</template>
<script setup lang="ts">
  import { onMounted, reactive, ref } from 'vue';
  import { message, Modal } from 'ant-design-vue';
  import { SmartLoading } from '/@/components/framework/smart-loading';
  import { messageApi } from '/@/api/support/message-api';
  import { PAGE_SIZE_OPTIONS } from '/@/constants/common-const';
  import { smartSentry } from '/@/lib/smart-sentry';
  import SmartEnumSelect from '/@/components/framework/smart-enum-select/index.vue';
  import TableOperator from '/@/components/support/table-operator/index.vue';
  import MessageSendForm from './components/message-send-form.vue';
  import { TABLE_ID_CONST } from '/@/constants/support/table-id-const';
  import { formatDateTime } from '/@/lib/datetime-util';
  // ---------------------------- 表格列 ----------------------------

  const columns = ref([
    {
      title: '消息类型',
      dataIndex: 'messageType',
      ellipsis: true,
      width: 100,
    },
    {
      title: '消息标题',
      dataIndex: 'title',
      ellipsis: true,
    },
    {
      title: '消息内容',
      dataIndex: 'content',
      ellipsis: true,
    },
    {
      title: '接收人ID',
      dataIndex: 'receiverUserId',
      ellipsis: true,
      width: 100,
    },
    {
      title: '已读',
      dataIndex: 'readFlag',
      width: 50,
    },
    {
      title: '已读时间',
      dataIndex: 'readTime',
      width: 150,
    },
    {
      title: '创建时间',
      dataIndex: 'createTime',
      width: 150,
    },
    {
      title: '操作',
      dataIndex: 'action',
      fixed: 'right',
      width: 60,
    },
  ]);

  // ---------------------------- 查询数据表单和方法 ----------------------------

  const queryFormState = {
    searchWord: undefined, //关键词
    pageNum: 1,
    pageSize: 10,
    createTime: [],
    readFlag: null,
    startDate: null,
    endDate: null,
    messageType: null,
  };
  function onChangeCreateTime(dates, dateStrings) {
    queryForm.startDate = dateStrings[0];
    queryForm.endDate = dateStrings[1];
  }
  // 查询表单form
  const queryForm = reactive({ ...queryFormState });
  // 表格加载loading
  const tableLoading = ref(false);
  // 表格数据
  const tableData = ref([]);
  // 总数
  const total = ref(0);

  // 重置查询条件
  function resetQuery() {
    let pageSize = queryForm.pageSize;
    Object.assign(queryForm, queryFormState);
    queryForm.pageSize = pageSize;
    queryData();
  }

  function searchQuery() {
    queryForm.pageNum = 1;
    queryData();
  }

  // 查询数据
  async function queryData() {
    tableLoading.value = true;
    try {
      let queryResult = await messageApi.queryAdminMessage(queryForm);
      tableData.value = queryResult.data.list;
      total.value = queryResult.data.total;
    } catch (e) {
      smartSentry.captureError(e);
    } finally {
      tableLoading.value = false;
    }
  }

  onMounted(queryData);

  // ---------------------------- 添加/修改 ----------------------------
  const formRef = ref();

  function showForm(data) {
    formRef.value.show(data);
  }

  //确认删除
  function onDelete(data) {
    Modal.confirm({
      title: '提示',
      content: '确定要删除选吗?',
      okText: '删除',
      okType: 'danger',
      onOk() {
        requestDelete(data);
      },
      cancelText: '取消',
      onCancel() {},
    });
  }

  async function requestDelete(data) {
    try {
      SmartLoading.show();
      await messageApi.deleteMessage(data.messageId);
      message.success('删除成功');
      queryData();
    } catch (e) {
      smartSentry.captureError(e);
    } finally {
      SmartLoading.hide();
    }
  }
</script>

// smart-admin-web-react/src/views/support/message/MessageList.tsx
/**
 * Message List (Admin View)
 *
 * Corresponds to Vue's support/message/message-list.vue (240L)
 * Admin view for managing and sending messages.
 */
import React, { useCallback, useEffect, useState } from 'react';
import { Card, Table, Input, Button, Space, DatePicker, Modal, message } from 'antd';
import { messageApi } from '@/api/support/message-api';
import type { MessageVO } from '@/types/message.types';
import type { ColumnsType } from 'antd/es/table';
import MessageSendForm from './MessageSendForm';
import type { DateRangeValue } from '@/types/date-range.types';

const { RangePicker } = DatePicker;
const PAGE_SIZE = 10;

const MessageList: React.FC = () => {
  const [data, setData] = useState<MessageVO[]>([]);
  const [loading, setLoading] = useState(false);
  const [total, setTotal] = useState(0);
  const [pageNum, setPageNum] = useState(1);
  const [keywords, setKeywords] = useState('');
  const [dateRange, setDateRange] = useState<DateRangeValue>(null);
  const [sendFormOpen, setSendFormOpen] = useState(false);

  const queryList = useCallback(async (page: number) => {
    setLoading(true);
    try {
      const res = await messageApi.query({
        searchWord: keywords,
        startDate: dateRange?.[0]?.format('YYYY-MM-DD'),
        endDate: dateRange?.[1]?.format('YYYY-MM-DD'),
        pageNum: page,
        pageSize: PAGE_SIZE,
      });
      if (res.code === 1 && res.data) {
        setData(res.data.list || []);
        setTotal(res.data.total || 0);
      }
    } finally {
      setLoading(false);
    }
  }, [keywords, dateRange]);

  useEffect(() => {
    queryList(1);
  }, []); // eslint-disable-line react-hooks/exhaustive-deps

  const handleSearch = () => { setPageNum(1); queryList(1); };
  const handleReset = () => { setKeywords(''); setDateRange(null); setPageNum(1); queryList(1); };

  const handleDelete = (messageId: number) => {
    Modal.confirm({
      title: '提示',
      content: '确定要删除该消息么？',
      okText: '确定', okType: 'danger', cancelText: '取消',
      async onOk() {
        await messageApi.delete(messageId);
        message.success('删除成功');
        queryList(pageNum);
      },
    });
  };

  const columns: ColumnsType<MessageVO> = [
    { title: '标题', dataIndex: 'title', ellipsis: true },
    { title: '类型', dataIndex: 'messageTypeName', width: 100 },
    { title: '内容', dataIndex: 'content', ellipsis: true },
    { title: '已读', dataIndex: 'readFlag', width: 60, render: (val) => val ? '是' : '否' },
    { title: '时间', dataIndex: 'createTime', width: 180 },
    {
      title: '操作',
      width: 60,
      align: 'center',
      render: (_, record) => (
        <a style={{ color: '#ff4d4f' }} onClick={() => handleDelete(record.messageId)}>删除</a>
      ),
    },
  ];

  return (
    <Card>
      <Space style={{ marginBottom: 16 }} wrap>
        <Input style={{ width: 200 }} value={keywords} onChange={(e) => setKeywords(e.target.value)} placeholder="标题/内容" allowClear />
        <RangePicker value={dateRange} onChange={(val) => setDateRange(val)} />
        <Button type="primary" onClick={handleSearch}>查询</Button>
        <Button onClick={handleReset}>重置</Button>
        <Button type="primary" onClick={() => setSendFormOpen(true)}>发送消息</Button>
      </Space>

      <Table
        rowKey="messageId"
        columns={columns}
        dataSource={data}
        loading={loading}
        size="small"
        pagination={{
          current: pageNum, pageSize: PAGE_SIZE, total,
          showTotal: (t) => `共${t}条`,
          onChange: (page) => { setPageNum(page); queryList(page); },
        }}
      />

      <MessageSendForm
        open={sendFormOpen}
        onCancel={() => setSendFormOpen(false)}
        onSuccess={() => { setSendFormOpen(false); queryList(pageNum); }}
      />
    </Card>
  );
};

export default MessageList;
