// smart-admin-web/src/views/system/department/department-list.vue
<template>
  <a-form class="smart-query-form">
    <a-row class="smart-query-form-row">
      <a-form-item label="部门名称" class="smart-query-form-item">
        <a-input style="width: 300px" v-model:value="keywords" placeholder="请输入部门名称" />
      </a-form-item>

      <a-form-item class="smart-query-form-item smart-margin-left10">
        <a-button-group>
          <a-button v-privilege="'support:department:query'" type="primary" @click="onSearch">
            <template #icon>
              <SearchOutlined />
            </template>
            查询
          </a-button>
          <a-button v-privilege="'support:department:query'" @click="resetQuery">
            <template #icon>
              <ReloadOutlined />
            </template>
            重置
          </a-button>
        </a-button-group>
        <a-button v-privilege="'system:department:add'" type="primary" @click="addDepartment" class="smart-margin-left20">
          <template #icon>
            <PlusOutlined />
          </template>
          新建
        </a-button>
      </a-form-item>
    </a-row>
  </a-form>

  <a-card size="small" :bordered="true">
    <a-table
      size="small"
      bordered
      :loading="tableLoading"
      rowKey="departmentId"
      :columns="columns"
      :data-source="departmentTreeData"
      :defaultExpandAllRows="false"
      :defaultExpandedRowKeys="defaultExpandedRowList"
      :pagination="false"
    >
      <template #bodyCell="{ text, record, column }">
        <template v-if="column.dataIndex === 'createTime' || column.dataIndex === 'updateTime'">
          {{ formatDateTime(text) }}
        </template>
        <template v-if="column.dataIndex === 'action'">
          <div class="smart-table-operate">
            <a-button @click="addDepartment(record)" v-privilege="'system:department:add'" type="link">添加下级</a-button>
            <a-button @click="updateDepartment(record)" v-privilege="'system:department:update'" type="link">编辑</a-button>
            <a-button
              danger
              v-if="record.departmentId !== topDepartmentId"
              v-privilege="'system:department:delete'"
              @click="deleteDepartment(record.departmentId)"
              type="link"
              >删除</a-button
            >
          </div>
        </template>
      </template>
    </a-table>
    <!-- 添加编辑部门弹窗 -->
    <DepartmentFormModal ref="departmentFormModal" @refresh="queryDepartmentTree" />
  </a-card>
</template>

<script setup lang="ts">
  import { onMounted, reactive, ref, watch, createVNode } from 'vue';
  import { departmentApi } from '/@/api/system/department-api';
  import { Modal } from 'ant-design-vue';
  import { ExclamationCircleOutlined } from '@ant-design/icons-vue';
  import _ from 'lodash';
  import { SmartLoading } from '/@/components/framework/smart-loading';
  import DepartmentFormModal from './components/department-form-modal.vue';
  import { smartSentry } from '/@/lib/smart-sentry';
  import { formatDateTime } from '/@/lib/datetime-util';

  const DEPARTMENT_PARENT_ID = 0;

  // -----------------------  筛选 ---------------------
  const keywords = ref('');

  // ----------------------- 部门树的展示 ---------------------
  const tableLoading = ref(false);

  const topDepartmentId = ref();
  // 所有部门列表
  const departmentList = ref([]);
  // 部门树形数据
  const departmentTreeData = ref([]);
  // 存放部门id和部门，用于查找
  const idInfoMap = ref(new Map());
  // 默认展开的行
  const defaultExpandedRowList = reactive([]);

  const columns = ref([
    {
      title: '部门名称',
      dataIndex: 'departmentName',
      key: 'departmentName',
    },
    {
      title: '负责人',
      dataIndex: 'managerName',
      key: 'managerName',
      width: 100,
    },
    {
      title: '排序',
      dataIndex: 'sort',
      key: 'sort',
      width: 100,
    },
    {
      title: '创建时间',
      dataIndex: 'createTime',
      width: 150,
    },
    {
      title: '更新时间',
      dataIndex: 'updateTime',
      width: 150,
    },
    {
      title: '操作',
      dataIndex: 'action',
      fixed: 'right',
      width: 200,
    },
  ]);

  onMounted(() => {
    queryDepartmentTree();
  });

  // 查询部门列表并构建 部门树
  async function queryDepartmentTree() {
    try {
      tableLoading.value = true;
      let res = await departmentApi.queryAllDepartment();
      let data = res.data;

      data.forEach((e) => {
        idInfoMap.value.set(e.departmentId, e);
      });

      departmentList.value = data;
      departmentTreeData.value = buildDepartmentTree(data, DEPARTMENT_PARENT_ID);

      // 默认显示 最顶级ID为列表中返回的第一条数据的ID
      if (!_.isEmpty(departmentTreeData.value) && departmentTreeData.value.length > 0) {
        topDepartmentId.value = departmentTreeData.value[0].departmentId;
      }

      defaultExpandedRowList.value = [];
      defaultExpandedRowList.push(topDepartmentId.value);
    } catch (e) {
      smartSentry.captureError(e);
    } finally {
      tableLoading.value = false;
    }
  }

  // 构建部门树
  function buildDepartmentTree(data, parentId) {
    let children = data.filter((e) => e.parentId === parentId) || [];
    if (!_.isEmpty(children)) {
      children.forEach((e) => {
        e.children = buildDepartmentTree(data, e.departmentId);
      });
      return children;
    }
    return null;
  }

  // 重置
  function resetQuery() {
    keywords.value = '';
    onSearch();
  }

  // 搜索
  function onSearch() {
    if (!keywords.value) {
      departmentTreeData.value = buildDepartmentTree(departmentList.value, DEPARTMENT_PARENT_ID);
      return;
    }
    let originData = departmentList.value.concat();
    if (!originData) {
      return;
    }
    // 筛选出名称符合的部门
    let filterDepartment = originData.filter((e) => e.departmentName.indexOf(keywords.value) > -1);
    let filterDepartmentList = [];
    // 循环筛选出的部门 构建部门树
    filterDepartment.forEach((e) => {
      recursionFilterDepartment(filterDepartmentList, e.departmentId, false);
    });
    departmentTreeData.value = buildDepartmentTree(filterDepartmentList, DEPARTMENT_PARENT_ID);
  }

  // 根据ID递归筛选部门
  function recursionFilterDepartment(resList, id, unshift) {
    let info = idInfoMap.value.get(id);
    if (!info || resList.some((e) => e.departmentId === id)) {
      return;
    }
    if (unshift) {
      resList.unshift(info);
    } else {
      resList.push(info);
    }
    if (info.parentId && info.parentId !== 0) {
      recursionFilterDepartment(resList, info.parentId, unshift);
    }
  }

  // ----------------------- 表单操作：添加部门/修改部门/删除部门/上下移动 ---------------------
  const departmentFormModal = ref();
  // 添加
  function addDepartment(e) {
    let data = {
      departmentId: 0,
      departmentName: '',
      parentId: e.departmentId || null,
    };
    departmentFormModal.value.showModal(data);
  }
  // 编辑
  function updateDepartment(e) {
    departmentFormModal.value.showModal(e);
  }

  // 删除
  function deleteDepartment(id) {
    Modal.confirm({
      title: '提醒',
      icon: createVNode(ExclamationCircleOutlined),
      content: '确定要删除该部门吗?',
      okText: '删除',
      okType: 'danger',
      async onOk() {
        SmartLoading.show();
        try {
          await departmentApi.deleteDepartment(id);
          await queryDepartmentTree();
        } catch (error) {
          smartSentry.captureError(error);
        } finally {
          SmartLoading.hide();
        }
      },
      cancelText: '取消',
      onCancel() {},
    });
  }
</script>

<style scoped lang="less"></style>

// smart-admin-web-react/src/views/system/department/DepartmentList.tsx
/**
 * Department List Page (Tree Table)
 *
 * Corresponds to Vue's views/system/department/department-list.vue
 */
import React, { useState, useEffect, useCallback, useMemo } from 'react';
import { Table, Input, Space, Modal, Card, Form, message } from 'antd';
import type { ColumnsType } from 'antd/es/table';
import { SearchOutlined, ReloadOutlined, PlusOutlined } from '@ant-design/icons';
import { PrivilegeButton } from '@/components/framework/privilege/PrivilegeButton';
import { departmentApi } from '@/api/system/department-api';
import type { DepartmentVO } from '@/types/department.types';
import DepartmentFormModal from './DepartmentFormModal';

const DEPARTMENT_PARENT_ID = 0;

/** Build tree from flat department list */
function buildDepartmentTree(data: DepartmentVO[], parentId: number): DepartmentVO[] | undefined {
  const children = data.filter((e) => e.parentId === parentId);
  if (children.length === 0) return undefined;
  return children.map((child) => ({
    ...child,
    children: buildDepartmentTree(data, child.departmentId) ?? undefined,
  }));
}

const DepartmentList: React.FC = () => {
  const [keywords, setKeywords] = useState('');
  const [loading, setLoading] = useState(false);
  const [departmentList, setDepartmentList] = useState<DepartmentVO[]>([]);
  const [treeData, setTreeData] = useState<DepartmentVO[]>([]);
  const [defaultExpandedRowKeys, setDefaultExpandedRowKeys] = useState<number[]>([]);
  const [modalVisible, setModalVisible] = useState(false);
  const [currentRecord, setCurrentRecord] = useState<Partial<DepartmentVO> | null>(null);

  // Top department ID (first root node)
  const topDepartmentId = useMemo(() => {
    if (treeData.length > 0) return treeData[0].departmentId;
    return undefined;
  }, [treeData]);

  // Build ID map for search filtering
  const idInfoMap = useMemo(() => {
    const map = new Map<number, DepartmentVO>();
    departmentList.forEach((e) => map.set(e.departmentId, e));
    return map;
  }, [departmentList]);

  const queryDepartmentTree = useCallback(async () => {
    setLoading(true);
    try {
      const res = await departmentApi.listAll();
      if (res.code === 1 && res.data) {
        setDepartmentList(res.data);
        const tree = buildDepartmentTree(res.data, DEPARTMENT_PARENT_ID) ?? [];
        setTreeData(tree);
        if (tree.length > 0) {
          setDefaultExpandedRowKeys([tree[0].departmentId]);
        }
      }
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    queryDepartmentTree();
  }, [queryDepartmentTree]);

  // Search: filter by keyword, include parent chain
  const handleSearch = () => {
    if (!keywords) {
      setTreeData(buildDepartmentTree(departmentList, DEPARTMENT_PARENT_ID) ?? []);
      return;
    }
    const filtered = departmentList.filter(
      (e) => e.departmentName.indexOf(keywords) > -1
    );
    const resultList: DepartmentVO[] = [];
    const addedIds = new Set<number>();

    function addWithParents(id: number) {
      if (addedIds.has(id)) return;
      const info = idInfoMap.get(id);
      if (!info) return;
      addedIds.add(id);
      resultList.push(info);
      if (info.parentId && info.parentId !== 0) {
        addWithParents(info.parentId);
      }
    }

    filtered.forEach((e) => addWithParents(e.departmentId));
    setTreeData(buildDepartmentTree(resultList, DEPARTMENT_PARENT_ID) ?? []);
  };

  const handleReset = () => {
    setKeywords('');
    setTreeData(buildDepartmentTree(departmentList, DEPARTMENT_PARENT_ID) ?? []);
  };

  const handleAdd = (parentRecord?: DepartmentVO) => {
    setCurrentRecord({
      departmentId: 0,
      departmentName: '',
      parentId: parentRecord?.departmentId ?? undefined,
    });
    setModalVisible(true);
  };

  const handleEdit = (record: DepartmentVO) => {
    setCurrentRecord(record);
    setModalVisible(true);
  };

  const handleDelete = (departmentId: number) => {
    Modal.confirm({
      title: '提醒',
      content: '确定要删除该部门吗?',
      okText: '删除',
      okType: 'danger',
      cancelText: '取消',
      onOk: async () => {
        const res = await departmentApi.delete(departmentId);
        if (res.code === 1) {
          message.success('删除成功');
          queryDepartmentTree();
        }
      },
    });
  };

  const columns: ColumnsType<DepartmentVO> = [
    { title: '部门名称', dataIndex: 'departmentName', key: 'departmentName' },
    { title: '负责人', dataIndex: 'managerName', key: 'managerName', width: 100 },
    { title: '排序', dataIndex: 'sort', key: 'sort', width: 100 },
    { title: '创建时间', dataIndex: 'createTime', width: 150 },
    { title: '更新时间', dataIndex: 'updateTime', width: 150 },
    {
      title: '操作',
      key: 'action',
      fixed: 'right',
      width: 200,
      render: (_: unknown, record: DepartmentVO) => (
        <Space>
          <PrivilegeButton permissionCode="system:department:add" type="link" size="small" onClick={() => handleAdd(record)}>
            添加下级
          </PrivilegeButton>
          <PrivilegeButton permissionCode="system:department:update" type="link" size="small" onClick={() => handleEdit(record)}>
            编辑
          </PrivilegeButton>
          {record.departmentId !== topDepartmentId && (
            <PrivilegeButton
              permissionCode="system:department:delete"
              type="link"
              size="small"
              danger
              onClick={() => handleDelete(record.departmentId)}
            >
              删除
            </PrivilegeButton>
          )}
        </Space>
      ),
    },
  ];

  return (
    <div style={{ padding: 24 }}>
      <Form layout="inline" style={{ marginBottom: 16 }}>
        <Form.Item label="部门名称">
          <Input
            style={{ width: 300 }}
            value={keywords}
            onChange={(e) => setKeywords(e.target.value)}
            onPressEnter={handleSearch}
            placeholder="请输入部门名称"
          />
        </Form.Item>
        <Form.Item>
          <Space>
            <PrivilegeButton permissionCode="support:department:query" type="primary" icon={<SearchOutlined />} onClick={handleSearch}>
              查询
            </PrivilegeButton>
            <PrivilegeButton permissionCode="support:department:query" icon={<ReloadOutlined />} onClick={handleReset}>
              重置
            </PrivilegeButton>
            <PrivilegeButton permissionCode="system:department:add" type="primary" icon={<PlusOutlined />} onClick={() => handleAdd()}>
              新建
            </PrivilegeButton>
          </Space>
        </Form.Item>
      </Form>

      <Card size="small" bordered>
        <Table
          size="small"
          bordered
          loading={loading}
          rowKey="departmentId"
          columns={columns}
          dataSource={treeData}
          defaultExpandedRowKeys={defaultExpandedRowKeys}
          pagination={false}
        />
      </Card>

      <DepartmentFormModal
        visible={modalVisible}
        record={currentRecord}
        onCancel={() => setModalVisible(false)}
        onSuccess={() => {
          setModalVisible(false);
          queryDepartmentTree();
        }}
      />
    </div>
  );
};

export default DepartmentList;
