// smart-admin-web-react/src/views/support/reload/ReloadResultList.tsx
/**
 * Reload Result List Modal
 *
 * Corresponds to Vue's support/reload/components/reload-result-list.vue (105L)
 */
import React, { useCallback, useEffect, useState } from 'react';
import { Modal, Table, Tag, Button } from 'antd';
import { ReloadOutlined } from '@ant-design/icons';
import { reloadApi } from '@/api/support/reload-api';
import type { ReloadResultVO } from '@/api/support/reload-api';
import type { ColumnsType } from 'antd/es/table';

interface Props {
  open: boolean;
  tag: string;
  onCancel: () => void;
}

const ReloadResultList: React.FC<Props> = ({ open, tag, onCancel }) => {
  const [data, setData] = useState<ReloadResultVO[]>([]);
  const [loading, setLoading] = useState(false);

  const queryResults = useCallback(async () => {
    setLoading(true);
    try {
      const res = await reloadApi.queryReloadResult(tag);
      if (res.code === 1 && res.data) {
        setData(res.data);
      }
    } finally {
      setLoading(false);
    }
  }, [tag]);

  useEffect(() => {
    if (open) {
      queryResults();
    }
  }, [open, queryResults]);

  const columns: ColumnsType<ReloadResultVO> = [
    { title: 'Tag', dataIndex: 'tag', width: 160 },
    { title: 'Args', dataIndex: 'args', ellipsis: true },
    {
      title: '结果',
      dataIndex: 'result',
      width: 80,
      align: 'center',
      render: (val) => <Tag color={val ? 'success' : 'error'}>{val ? '成功' : '失败'}</Tag>,
    },
    { title: '异常', dataIndex: 'exception', ellipsis: true },
    { title: '时间', dataIndex: 'createTime', width: 180 },
  ];

  return (
    <Modal
      title={
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', paddingRight: 24 }}>
          <span>执行结果</span>
          <Button size="small" icon={<ReloadOutlined />} onClick={queryResults}>刷新</Button>
        </div>
      }
      open={open}
      onCancel={onCancel}
      footer={null}
      width={800}
      destroyOnClose
    >
      <Table
        rowKey={(_, i) => String(i)}
        columns={columns}
        dataSource={data}
        loading={loading}
        size="small"
        pagination={false}
        scroll={{ y: 350 }}
      />
    </Modal>
  );
};

export default ReloadResultList;

// smart-admin-web/src/views/support/reload/reload-result-list.vue
<!--
  * reload 结果
  * 
  * @Author:    1024创新实验室-主任：卓大 
  * @Date:      2022-07-21 21:55:12
  * @Wechat:    zhuda1024 
  * @Email:     lab1024@163.com 
  * @Copyright  1024创新实验室 （ https://1024lab.net ），Since 2012 
-->
<template>
  <a-modal :open="visible" title="reload结果列表" width="60%" :footer="null" @cancel="onClose">
    <a-button type="primary" @click="ajaxQuery" size="small">
      <template #icon>
        <ReloadOutlined />
      </template>
      刷新
    </a-button>
    <a-table :scroll="{ y: 350 }" size="small" bordered rowKey="id" class="smart-margin-top10" :dataSource="tableData" :columns="columns">
      <template #bodyCell="{ text, column }">
        <template v-if="column.dataIndex === 'createTime'">
          {{ formatDateTime(text) }}
        </template>

        <template v-if="column.dataIndex === 'result'">
          <a-tag :color="text ? 'success' : 'error'">{{ text ? '成功' : '失败' }}</a-tag>
        </template>
      </template>
      <template #expandedRowRender="{ record }">
        <pre style="margin: 0; font-size: 12px">
          {{ record.exception }}
        </pre>
      </template>
    </a-table>
  </a-modal>
</template>
<script setup lang="ts">
  import { reactive, ref } from 'vue';
  import { reloadApi } from '/@/api/support/reload-api';
  import { smartSentry } from '/@/lib/smart-sentry';
  import { formatDateTime } from '/@/lib/datetime-util';
  defineExpose({
    showModal,
  });

  // ----------------------- 表单 隐藏 与 显示 ------------------------
  // 是否展示
  const visible = ref(false);

  function showModal(tag) {
    queryTag = tag;
    ajaxQuery();
    visible.value = true;
  }

  function onClose() {
    visible.value = false;
  }

  //------------------------ 表格查询 ---------------------
  let queryTag = '';
  const tableLoading = ref(false);
  const tableData = ref([]);

  async function ajaxQuery() {
    try {
      tableLoading.value = true;
      let res = await reloadApi.queryReloadResult(queryTag);
      let count = 1;
      for (const item of res.data) {
        item.id = count++;
      }
      tableData.value = res.data;
    } catch (e) {
      smartSentry.captureError(e);
    } finally {
      tableLoading.value = false;
    }
  }

  //------------------------ 表格列 ---------------------

  const columns = reactive([
    {
      title: '标签',
      dataIndex: 'tag',
    },
    {
      title: '参数',
      dataIndex: 'args',
    },
    {
      title: '运行结果',
      dataIndex: 'result',
    },
    {
      title: '异常',
      dataIndex: 'exception',
      ellipsis: true,
    },
    {
      title: '创建时间',
      dataIndex: 'createTime',
    },
  ]);
</script>
