// smart-admin-web-react/src/views/support/help-doc/components/HelpDocList.tsx
/**
 * Help Doc List
 * 幫助文檔列表
 *
 * @Author: SmartAdmin React Team
 * @Date: 2026-03-14
 */

import React, { useEffect, useState, useRef } from 'react';
import { Form, Input, Button, Card, Table, Space, DatePicker, Modal } from 'antd';
import { SearchOutlined, ReloadOutlined, PlusOutlined } from '@ant-design/icons';
import type { ColumnsType } from 'antd/es/table';
import dayjs, { type Dayjs } from 'dayjs';
import { helpDocApi } from '@/api/support/helpDocApi';
import { usePrivilege } from '@/hooks/usePrivilege';
import { HELP_DOC_PERMISSION, HELP_DOC_TABLE_COLUMNS_WIDTH } from '@/constants/support/helpDocConst';
import type { HelpDocVO, HelpDocQueryForm } from '../types';
import HelpDocFormDrawer, { type HelpDocFormDrawerRef } from './HelpDocFormDrawer';
import { Link } from 'react-router-dom';

const { RangePicker } = DatePicker;
const { confirm } = Modal;

export interface HelpDocListProps {
  helpDocCatalogId?: number | null;
}

const HelpDocList: React.FC<HelpDocListProps> = ({ helpDocCatalogId }) => {
  const [form] = Form.useForm<HelpDocQueryForm>();
  const hasQueryPrivilege = usePrivilege(HELP_DOC_PERMISSION.QUERY);
  const hasAddPrivilege = usePrivilege(HELP_DOC_PERMISSION.ADD);
  const hasUpdatePrivilege = usePrivilege(HELP_DOC_PERMISSION.UPDATE);
  const hasDeletePrivilege = usePrivilege(HELP_DOC_PERMISSION.DELETE);

  const [tableData, setTableData] = useState<HelpDocVO[]>([]);
  const [tableLoading, setTableLoading] = useState(false);
  const [total, setTotal] = useState(0);
  const [createDate, setCreateDate] = useState<[Dayjs, Dayjs] | null>(null);

  const helpDocFormDrawerRef = useRef<HelpDocFormDrawerRef>(null);

  useEffect(() => {
    form.setFieldsValue({
      helpDocCatalogId,
      pageNum: 1,
      pageSize: 10,
    });
    fetchData();
  }, [helpDocCatalogId]);

  const fetchData = async () => {
    if (!hasQueryPrivilege) {
      return;
    }

    try {
      setTableLoading(true);
      const values = form.getFieldsValue();
      const res = await helpDocApi.query({
        ...values,
        helpDocCatalogId: helpDocCatalogId || null,
      });

      setTableData(res.data.list);
      setTotal(res.data.total);
    } catch (error) {
      console.error('Failed to fetch help doc list:', error);
    } finally {
      setTableLoading(false);
    }
  };

  const handleSearch = () => {
    form.setFieldsValue({ pageNum: 1 });
    fetchData();
  };

  const handleReset = () => {
    form.resetFields();
    form.setFieldsValue({
      pageNum: 1,
      pageSize: 10,
      helpDocCatalogId,
    });
    setCreateDate(null);
    fetchData();
  };

  const handleTableChange = (page: number, pageSize: number) => {
    form.setFieldsValue({ pageNum: page, pageSize });
    fetchData();
  };

  const handleCreateDateChange = (dates: [Dayjs, Dayjs] | null) => {
    setCreateDate(dates);
    if (dates) {
      form.setFieldsValue({
        createTimeBegin: dates[0].format('YYYY-MM-DD'),
        createTimeEnd: dates[1].format('YYYY-MM-DD'),
      });
    } else {
      form.setFieldsValue({
        createTimeBegin: null,
        createTimeEnd: null,
      });
    }
  };

  const handleAddOrUpdate = (helpDocId?: number) => {
    helpDocFormDrawerRef.current?.showDrawer(helpDocId);
  };

  const handleDelete = (helpDocId: number) => {
    confirm({
      title: '提示',
      content: '確認刪除此數據嗎?',
      onOk: async () => {
        try {
          await helpDocApi.delete(helpDocId);
          fetchData();
        } catch (error) {
          console.error('Failed to delete help doc:', error);
        }
      },
    });
  };

  const columns: ColumnsType<HelpDocVO> = [
    {
      title: '標題',
      dataIndex: 'title',
      key: 'title',
      width: HELP_DOC_TABLE_COLUMNS_WIDTH.title,
      ellipsis: true,
      render: (text: string, record: HelpDocVO) => (
        <Link to={`/help-doc/detail?helpDocId=${record.helpDocId}`} target="_blank">
          {text}
        </Link>
      ),
    },
    {
      title: '目錄',
      dataIndex: 'helpDocCatalogName',
      key: 'helpDocCatalogName',
      width: HELP_DOC_TABLE_COLUMNS_WIDTH.helpDocCatalogName,
      ellipsis: true,
    },
    {
      title: '作者',
      dataIndex: 'author',
      key: 'author',
      width: HELP_DOC_TABLE_COLUMNS_WIDTH.author,
      ellipsis: true,
    },
    {
      title: '排序',
      dataIndex: 'sort',
      key: 'sort',
      width: HELP_DOC_TABLE_COLUMNS_WIDTH.sort,
    },
    {
      title: '頁面瀏覽量',
      dataIndex: 'pageViewCount',
      key: 'pageViewCount',
      width: HELP_DOC_TABLE_COLUMNS_WIDTH.pageViewCount,
    },
    {
      title: '用戶瀏覽量',
      dataIndex: 'userViewCount',
      key: 'userViewCount',
      width: HELP_DOC_TABLE_COLUMNS_WIDTH.userViewCount,
    },
    {
      title: '創建時間',
      dataIndex: 'createTime',
      key: 'createTime',
      width: HELP_DOC_TABLE_COLUMNS_WIDTH.createTime,
    },
    {
      title: '操作',
      dataIndex: 'action',
      key: 'action',
      fixed: 'right',
      width: HELP_DOC_TABLE_COLUMNS_WIDTH.action,
      render: (_: any, record: HelpDocVO) => (
        <div>
          {hasUpdatePrivilege && (
            <Button
              type="link"
              size="small"
              onClick={() => handleAddOrUpdate(record.helpDocId)}
            >
              編輯
            </Button>
          )}
          {hasDeletePrivilege && (
            <Button
              type="link"
              size="small"
              danger
              onClick={() => handleDelete(record.helpDocId)}
            >
              刪除
            </Button>
          )}
        </div>
      ),
    },
  ];

  if (!hasQueryPrivilege) {
    return null;
  }

  return (
    <div style={{ height: '100%', display: 'flex', flexDirection: 'column' }}>
      <Form form={form} layout="inline" style={{ marginBottom: 16 }}>
        <Form.Item label="關鍵字">
          <Input
            value={form.getFieldValue('keywords')}
            onChange={(e) => form.setFieldValue('keywords', e.target.value)}
            placeholder="標題、作者"
            style={{ width: 300 }}
          />
        </Form.Item>

        <Form.Item label="創建時間">
          <RangePicker
            value={createDate}
            onChange={handleCreateDateChange}
            style={{ width: 220 }}
          />
        </Form.Item>

        <Form.Item name="pageNum" hidden>
          <Input />
        </Form.Item>

        <Form.Item name="pageSize" hidden>
          <Input />
        </Form.Item>

        <Form.Item name="createTimeBegin" hidden>
          <Input />
        </Form.Item>

        <Form.Item name="createTimeEnd" hidden>
          <Input />
        </Form.Item>

        <Form.Item name="helpDocCatalogId" hidden>
          <Input />
        </Form.Item>

        <Form.Item>
          <Space>
            <Button type="primary" icon={<SearchOutlined />} onClick={handleSearch}>
              查詢
            </Button>
            <Button icon={<ReloadOutlined />} onClick={handleReset}>
              重置
            </Button>
          </Space>
        </Form.Item>
      </Form>

      <Card size="small" style={{ flex: 1 }}>
        <div style={{ marginBottom: 16 }}>
          {hasAddPrivilege && (
            <Button
              type="primary"
              icon={<PlusOutlined />}
              onClick={() => handleAddOrUpdate()}
            >
              新建
            </Button>
          )}
        </div>

        <Table
          rowKey="helpDocId"
          columns={columns}
          dataSource={tableData}
          loading={tableLoading}
          pagination={{
            current: form.getFieldValue('pageNum') || 1,
            pageSize: form.getFieldValue('pageSize') || 10,
            total,
            showSizeChanger: true,
            showQuickJumper: true,
            showTotal: (total) => `共${total}條`,
            onChange: handleTableChange,
          }}
          size="small"
          bordered
          scroll={{ x: 1000 }}
        />
      </Card>

      <HelpDocFormDrawer ref={helpDocFormDrawerRef} onReloadList={fetchData} />
    </div>
  );
};

export default HelpDocList;

// smart-admin-web/src/views/support/help-doc/management/components/help-doc-list.vue
<!--
  * 帮助文档 列表
  *
  * @Author:    1024创新实验室-主任：卓大
  * @Date:      2022-07-21 21:55:12
  * @Wechat:    zhuda1024
  * @Email:     lab1024@163.com
  * @Copyright  1024创新实验室 （ https://1024lab.net ），Since 2012
-->
<template>
  <a-form class="smart-query-form" v-privilege="'support:helpDoc:query'">
    <a-row class="smart-query-form-row">
      <a-form-item label="关键字" class="smart-query-form-item">
        <a-input style="width: 300px" v-model:value="queryForm.keywords" placeholder="标题、作者" />
      </a-form-item>

      <a-form-item label="创建时间" class="smart-query-form-item">
        <a-range-picker :presets="defaultTimeRanges" v-model:value="createDate" @change="createDateChange" style="width: 220px" />
      </a-form-item>

      <a-form-item class="smart-query-form-item smart-margin-left10">
        <a-button-group>
          <a-button type="primary" @click="onSearch">
            <template #icon>
              <SearchOutlined />
            </template>
            查询
          </a-button>
          <a-button @click="onReload">
            <template #icon>
              <ReloadOutlined />
            </template>
            重置
          </a-button>
        </a-button-group>
      </a-form-item>
    </a-row>
  </a-form>

  <a-card size="small" :bordered="false">
    <a-row class="smart-table-btn-block">
      <div class="smart-table-operate-block">
        <a-button type="primary" @click="addOrUpdate()" v-privilege="'support:helpDoc:add'">
          <template #icon>
            <PlusOutlined />
          </template>
          新建
        </a-button>
      </div>
      <div class="smart-table-setting-block">
        <TableOperator v-model="tableColumns" :tableId="TABLE_ID_CONST.SUPPORT.HELP_DOC" :refresh="queryHelpDocList" />
      </div>
    </a-row>

    <a-table
      rowKey="helpDocId"
      :columns="tableColumns"
      :scroll="{ x: 1000 }"
      :dataSource="tableData"
      :pagination="false"
      :loading="tableLoading"
      size="small"
      bordered
    >
      <template #bodyCell="{ text, column, record }">
        <template v-if="column.dataIndex === 'createTime'">
          {{ formatDateTime(text) }}
        </template>

        <template v-if="column.dataIndex === 'title'">
          <router-link tag="a" target="_blank" :to="{ path: '/help-doc/detail', query: { helpDocId: record.helpDocId } }">{{
            record.title
          }}</router-link>
        </template>
        <template v-else-if="column.dataIndex === 'action'">
          <div class="smart-table-operate">
            <a-button type="link" @click="addOrUpdate(record.helpDocId)" v-privilege="'support:helpDoc:update'">编辑</a-button>
            <a-button type="link" danger @click="onDelete(record.helpDocId)" v-privilege="'support:helpDoc:delete'">删除</a-button>
          </div>
        </template>
      </template>
    </a-table>

    <div class="smart-query-table-page">
      <a-pagination
        showSizeChanger
        showQuickJumper
        show-less-items
        :pageSizeOptions="PAGE_SIZE_OPTIONS"
        :defaultPageSize="queryForm.pageSize"
        v-model:current="queryForm.pageNum"
        v-model:pageSize="queryForm.pageSize"
        :total="total"
        @change="queryHelpDocList"
        :show-total="(total) => `共${total}条`"
      />
    </div>
  </a-card>

  <HelpDocFormDrawer ref="helpDocFormDrawerRef" @reloadList="queryHelpDocList" />
</template>

<script setup lang="ts">
  import { message, Modal } from 'ant-design-vue';
  import { onMounted, reactive, ref, watch } from 'vue';
  import HelpDocFormDrawer from './help-doc-form-drawer.vue';
  import { helpDocApi } from '/@/api/support/help-doc-api';
  import { PAGE_SIZE, PAGE_SIZE_OPTIONS } from '/@/constants/common-const';
  import { smartSentry } from '/@/lib/smart-sentry';
  import TableOperator from '/@/components/support/table-operator/index.vue';
  import { defaultTimeRanges } from '/@/lib/default-time-ranges';
  import { TABLE_ID_CONST } from '/@/constants/support/table-id-const';
  import { formatDateTime } from '/@/lib/datetime-util';

  const props = defineProps({
    // 目录id
    helpDocCatalogId: Number,
  });

  const queryFormState = {
    helpDocCatalogId: props.helpDocCatalogId, //目录
    keywords: '', //标题、作者
    createTimeBegin: null, //创建-开始时间
    createTimeEnd: null, //创建-截止时间
    pageNum: 1,
    pageSize: PAGE_SIZE,
  };
  const queryForm = reactive({ ...queryFormState });

  const tableColumns = ref([
    {
      title: `标题`,
      dataIndex: 'title',
      ellipsis: true,
    },
    {
      title: '目录',
      dataIndex: 'helpDocCatalogName',
      width: 120,
      ellipsis: true,
    },
    {
      title: `作者`,
      dataIndex: 'author',
      width: 110,
      ellipsis: true,
    },
    {
      title: '排序',
      dataIndex: 'sort',
      width: 90,
    },
    {
      title: '页面浏览量',
      dataIndex: 'pageViewCount',
      width: 90,
    },
    {
      title: '用户浏览量',
      dataIndex: 'userViewCount',
      width: 90,
    },
    {
      title: '创建时间',
      dataIndex: 'createTime',
      width: 150,
    },
    {
      title: '操作',
      dataIndex: 'action',
      fixed: 'right',
      width: 90,
    },
  ]);

  // ------------------ 查询相关 ------------------

  const tableData = ref([]);
  const total = ref(0);
  const tableLoading = ref(false);

  onMounted(() => {
    queryHelpDocList();
  });

  // 查询列表
  async function queryHelpDocList() {
    try {
      tableLoading.value = true;
      const result = await helpDocApi.query(queryForm);
      tableData.value = result.data.list;
      total.value = result.data.total;
    } catch (err) {
      smartSentry.captureError(err);
    } finally {
      tableLoading.value = false;
    }
  }

  // 点击查询
  function onSearch() {
    queryForm.pageNum = 1;
    queryHelpDocList();
  }

  // 点击重置
  function onReload() {
    Object.assign(queryForm, queryFormState);
    publishDate.value = [];
    createDate.value = [];
    queryHelpDocList();
  }

  // 发布日期选择
  const publishDate = ref([]);
  function publishDateChange(dates, dateStrings) {
    queryForm.publishTimeBegin = dateStrings[0];
    queryForm.publishTimeEnd = dateStrings[1];
  }
  // 创建日期选择
  const createDate = ref([]);
  function createDateChange(dates, dateStrings) {
    queryForm.createTimeBegin = dateStrings[0];
    queryForm.createTimeEnd = dateStrings[1];
  }

  // ------------------ 新建、编辑 ------------------

  // 新建、编辑
  const helpDocFormDrawerRef = ref();
  function addOrUpdate(helpDocId) {
    helpDocFormDrawerRef.value.showModal(helpDocId);
  }

  // ------------------ 删除 ------------------

  // 删除
  function onDelete(helpDocId) {
    Modal.confirm({
      title: '提示',
      content: '确认删除此数据吗?',
      onOk() {
        deleteHelpDoc(helpDocId);
      },
    });
  }

  // 删除API
  async function deleteHelpDoc(helpDocId) {
    try {
      tableLoading.value = true;
      await helpDocApi.delete(helpDocId);
      message.success('删除成功');
      queryHelpDocList();
    } catch (err) {
      smartSentry.captureError(err);
    } finally {
      tableLoading.value = false;
    }
  }

  watch(
    () => props.helpDocCatalogId,
    () => {
      queryForm.helpDocCatalogId = props.helpDocCatalogId;
      onSearch();
    },
    { immediate: true }
  );
</script>

<style lang="less" scoped></style>
